# Generated by Django 6.0.5 on 2026-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='', max_length=50),
        ),
    ]
