# Generated by Django 6.0.5 on 2026-05-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.IntegerField()),
                ('imagen', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Platos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_personas', models.IntegerField()),
                ('id_genero', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(db_column='contraseña', max_length=255)),
                ('rol', models.CharField(blank=True, choices=[('admin', 'admin'), ('usuario', 'usuario')], default='usuario', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_plato', models.IntegerField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Favoritos',
                'unique_together': {('id_usuario', 'id_plato')},
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_genero', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Votos',
                'unique_together': {('id_usuario', 'id_genero')},
            },
        ),
    ]
