# Generated by Django 6.0.5 on 2026-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('idGenero', models.IntegerField()),
                ('fecha', models.IntegerField()),
            ],
        ),
    ]
