# Generated by Django 6.0.5 on 2026-05-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('numero_personas', models.IntegerField()),
                ('id_genero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
